# Generated by Django 5.1.1 on 2024-09-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
    ]
